version: '3.8'

services:
  demo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-spring-boot
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    restart: unless-stopped
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge